/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import FormClan.FormNoviClan;
import FormClan.FormPretragaClana;
import controller.ClientController;
import domain.Administrator;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    Administrator ulogovani;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani administrator: " + ulogovani);
        setTitle("Klijentska forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviClan = new javax.swing.JMenuItem();
        miPretragaClana = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miPretragaRezervacije = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jMenu6.setText("Clan");

        miNoviClan.setText("Novi clan");
        miNoviClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviClanActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviClan);

        miPretragaClana.setText("Pretraga clana");
        miPretragaClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaClanaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaClana);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Rezervacije");

        miPretragaRezervacije.setText("Pretraga rezervacije");
        miPretragaRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaRezervacijeActionPerformed(evt);
            }
        });
        jMenu7.add(miPretragaRezervacije);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Odjava");

        miOdjava.setText("Odjavi se sa sistema");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu8.add(miOdjava);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviClanActionPerformed
        new FormNoviClan(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviClanActionPerformed

    private void miPretragaClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaClanaActionPerformed
        new FormPretragaClana(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaClanaActionPerformed

    private void miPretragaRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaRezervacijeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretragaRezervacijeActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new LoginForma().setVisible(true);
            Session.getInstance().setUlogovani(null);
            this.dispose();
        }

    }//GEN-LAST:event_miOdjavaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNoviClan;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaClana;
    private javax.swing.JMenuItem miPretragaRezervacije;
    // End of variables declaration//GEN-END:variables

}
